### ISSUE TITLE
Error: [foxact] useClipboard: navigator.clipboard is not supported

### ISSUE THREAD

**Issue by tohsaka888** [SukkaW/foxact#5]
Hi,i am using foxact.

I deploy my web app using docker in private server.When i want to copy something using `useClipboard`, i got an error.

```bash
Error: [foxact] useClipboard: navigator.clipboard is not supported
``` 

How can i fix it?

**Comment by SukkaW** [comment]
It seems that the browser has blocked access to the `navigator.clipboard` API.

Try this:

```tsx
const { copy, error } = useClipboard({ usePromptAsFallback: true });
```

With this option, foxact will attempt to use `window.prompt` to provide a fallback for a manual copy.

**Comment by tohsaka888** [comment]
Thanks!!!
